modLoader="javafml"
loaderVersion="[25,)"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="modernity"
version="${file.jarVersion}"
displayName="The Modernity"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="examplemod.png"
credits="Copyright (c) 2019 Red Galaxy and contributors."
authors="Red Galaxy"
description='''
A broken universe.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"