name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and publish
      run: ./gradlew publish
      env:
        mdKeyStore: ${{ secrets.mdKeyStore }}
        mdKeyStoreAlias: ${{ secrets.mdKeyStoreAlias }}
        mdKeyStorePass: ${{ secrets.mdKeyStorePass }}
        mdKeyStoreKeyPass: ${{ secrets.mdKeyStoreKeyPass }}
        mdSignSHA1: ${{ secrets.mdSignSHA1 }}
        gprUser: ${{ secrets.gprUser }}
        gprKey: ${{ secrets.gprKey }}
